### PR TITLE
Change ic, dic to tax_id, tax_id2

### PR DESCRIPTION
**Pull request by HCLarsen**
This should do it.

### CODE REVIEW

**Comment by HCLarsen** [comment]
Is there something wrong with my PR?

**Comment by strzibny** [comment]
Glad you commented again, it slipped my attention. Looking good! I will run the tests and if everything is good I merge.

**Comment by HCLarsen** [comment]
Great, let me know if there are any issues, and I'll fix them.

**Comment by strzibny** [comment]
@HCLarsen thanks again, merged.

**Comment by HCLarsen** [comment]
No problem. I'm happy to contribute.

**Pull request merged**
