### PR TITLE
try to clarify labels on feature list

### PR DESCRIPTION
**Pull request by combinatorist**

### CODE REVIEW

**Comment by combinatorist** [comment]
For #48

**Comment by strzibny** [comment]
If you are a native speaker, do you think there is a better equivalent / synonym for label in this context?

**Comment by combinatorist** [comment]
I don't think there's a simple one word that will cover it in American English at least. Label is actually a really good word, except that when it has anything to do with mail (as with printed invoices) then, we think of mailing address label instead of labeling the field on the form.

My best suggestions so far are to use a new phrase like "field label". Then, you can also have "field value" (as I've done in #51).

This makes it sort of like "key" / "value" which will at least help programmers understand.

Actually, it is probably even better to call it "field descriptions" but I would need to test it on other English speakers to be sure.

**Comment by strzibny** [comment]
Field label sounds like a good solution for the current docs since I don't need to change the API. Thanks!

**Comment by strzibny** [comment]
I am now calling them field labels and included full list in the command line docs as well.

**Pull request closed without merging**
