### PR TITLE
Change ic & dic to tax_id & tax_id2

### PR DESCRIPTION
**Pull request by HCLarsen**

### CODE REVIEW

**Comment by strzibny** [comment]
Thanks for the PR. Please change the labels keys as well (`labels[:ic]'). Also please use imperative style of commit messages ("Change ...to...." instead of "Changed to...").

**Comment by HCLarsen** [comment]
Ok, fixed both of those. Do I issue a new pull request, or is it possible to update this one?

**Comment by strzibny** [comment]
Would you be so kind and change also remaining places? There are new JSON serializers for one. Also make sure tests are passing (`$ rake test`). Once done, just squash the commits into one. No need for a new PR, quite the opposite, 1 pr and 1 commit for this change is ideal.

**Comment by HCLarsen** [comment]
I don't understand. I changed all places of ic and dic. I searched all the files in the repository, and there's no ic or dic left. I also don't know how to change it to 1 commit, as it automatically added a second commit when I pushed my changes to my forked repository.

**Comment by strzibny** [comment]
You need to rebase to current master with `git pull origin master --rebase`. (When `origin` is this very repository, e.g. `not` your fork.)

**Comment by HCLarsen** [comment]
That just destroyed my entire directory, and I have no idea how to fix it. I'm just going to delete my fork and start from scratch.

**Pull request closed without merging**
